### ISSUE TITLE
need to add dependsOn when use revealJs in 3.0.0-alpha.1

### ISSUE THREAD

**Issue by jagedn** [asciidoctor/asciidoctor-gradle-plugin#388] opened 2019-05-26 20:07 UTC
I'm trying to build a multibackend project (html, pdf, epub and slides) and include all of them:

```
plugins {
    id 'org.asciidoctor.jvm.convert' version '3.0.0-alpha.1'
    id 'org.asciidoctor.jvm.epub' version '3.0.0-alpha.1'
    id 'org.asciidoctor.jvm.pdf' version '3.0.0-alpha.1'
    id 'org.asciidoctor.jvm.revealjs' version '3.0.0-alpha.1'
}
```
If I run asciidoctor taks (or pdf or epub tasks) the build fails with:

```
> Task :asciidoctor
Exception in thread "main" org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor-revealjs
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:987)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.<main>(<script>:1)

```
but if `asciidoctor` tasks dependsOn `revealJs`all work fine

you can check this error with this project https://gitlab.com/puravida-asciidoctor/asciidoctor-amazon-template , branch 3.0.0-alpha.1  (and if you uncomment line 77 of the build.gradle file,  the task works)

**Comment by ysb33r** [comment] 2019-05-27 09:16
There should be no need for the dependsOn, but I think I know what the issue is here: Reveal plugin is affecting the global `asciidoctorj` extension` by adding a `requires` which will not be there, because `asciidoctorGemsPrepare` has not run yet.

Also I am not even sure whether this approach is a good thing or not. Maybe the plugin should rather add the requires to the task extension instead. Now if I follow that reasoning maybe the same should happen for the ePUB & Pdf task extensions too.

**Comment by ysb33r** [comment] 2019-05-27 12:25
WIll be in 3.0.0-alpha.2

**Closed** 2019-06-30 18:17 UTC
Labels: bug

**Comment by meisterplanlos** [comment] 2019-11-21 17:55
This problem still occurs with 3.0.0-alpha.3 (also tested with 3.0.0-alpha.2). Here is the build.gradle I use for testing. Remove revealjs from the plugins: everything works fine.

```
plugins {
    id 'org.asciidoctor.jvm.convert' version '3.0.0-alpha.3'
    id 'org.asciidoctor.jvm.pdf' version '3.0.0-alpha.3'

    // by remove the following line, everything works fine
    id 'org.asciidoctor.jvm.revealjs' version '3.0.0-alpha.3'
}

repositories {
  jcenter()
}

asciidoctor {
  sourceDir file(projectDir.getAbsolutePath())
  sources {
    include '**/*.adoc'
  }
  outputDir file(projectDir.getAbsolutePath() + '/build')
  outputOptions {
    backends = [ 'pdf' ]
  }
}

defaultTasks 'asciidoctor'
```
