### ISSUE TITLE
Task asciidoctor fails when having more than one backend

### ISSUE THREAD

**Issue by mariogarcia** [asciidoctor/asciidoctor-gradle-plugin#324] opened 2019-04-04 06:40 UTC
## Description

When configuring multiple backends `./gradlew ascii` fails even though executing `asciiEpub`, `asciiPdf` separately works. 

## Screenshot
![asciidoctor_gradle_exception](https://user-images.githubusercontent.com/1414131/55534365-819a8400-56b4-11e9-91d9-8a7bd5119a59.png)

## Source code

The `build.gradle` looks like this:

```groovy
plugins {
    id 'org.asciidoctor.jvm.pdf' version '2.0.0'
    id 'org.asciidoctor.jvm.epub' version '2.0.0'
    id 'org.asciidoctor.jvm.convert' version '2.0.0'
}

repositories {
    jcenter()
    mavenCentral()
}

asciidoctorEpub {
    ebookFormats = [EPUB3]

    sourceDir = 'src/docs/asciidoc'
    sources {
        include 'index.adoc'
    }
}

asciidoctorPdf {
    sourceDir = 'src/docs/asciidoc'
    sources {
        include 'index.adoc'
    }
}

asciidoctor {
    sourceDir = 'src/docs/asciidoc'

    outputOptions {
        backends = ['html5', 'pdf', 'epub'] // <--- ArrayIndexOutOfBoundsException
    }

    sources {
        include 'index.adoc'
    }
}
```

Anyway you can find the whole project here: https://github.com/mariogarcia/asciidoctor-gradle-samples/tree/master/multiple-backends

## Versions

- Gradle: 5.0
- JDK: 8.0.191-oracle

**Comment by jagedn** [comment] 2019-04-04 07:45
maybe related with https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/282

I tried with 

    outputOptions{
       backends = ['html5', 'epub']
    }

and it works

Also I tried to include the epub dependency as suggested in issue 282 using

    configurations {
        asciidoctorExt
    }
    dependencies {
        asciidoctorExt 'org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.8.1'
    }
    asciidoctor{     
         ....
         configurations 'asciidoctorExt'
    }

but error persists

**Comment by ysb33r** [comment] 2019-04-04 09:40
> backends = ['html5', 'pdf', 'epub']

@mariogarcia I'll have a look to see what the cause of the `ArrayIndexOutOfBoundsException` is.

Besides that: It is recommended to use the `asciidoctorEpub` task instead. If you plan to use the `epub` backend directly on the generic `asciidoctor` task it is you responsibility to place the epub artifact on the classpath. The correct way for that is to do

```groovy
asciidoctor {
  asciidoctorj {
      epubVersion = '1.5.0-alpha.8.1'
  }
}
```

Do hnot use the `configurations` property for that. In addition the epub plugin will ensure that `kindlegen` is available when using the `KF8` eBookFormat.

@jagedn Please note that #282 is related to 1.5.x and not applicable in this case.

**Comment by ysb33r** [comment] 2019-04-11 13:12
@mariogarcia You accidentally found a bug that is not really related to your usage. If there are more than two backends specified and there are no additional GEMs, then it causes the `ArrayIndexOutOfBoundsException`.

I'll fix that and then close this issue and the correct usage have been addressed in https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues?q=is%3Aopen+is%3Aissue+label%3A2.0.x#issuecomment-479826956.

**Comment by mariogarcia** [comment] 2019-04-13 10:41
Understood @ysb33r :+1:

**Closed** 2019-04-20 10:24 UTC
Labels: 2.x, bug, question
