### ISSUE TITLE
Warning message shown when using pdf backend

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-gradle-plugin#147] opened 2015-01-29 23:41 UTC
I have noticed that when using the `pdf` backend the following message is shown on the console:
````
Passing through unknown backend: pdf
```

Since pdf is not a final version (please, correct me if i am wrong) I don't see a warning as a bad thing, but saying 'unknown' seems confusing to me.

How about adding a second list of 'incubating' backends and showing something like:
```
Passing through a {preview|incubating|work-in-progess} backend. If you have any issue please report to ....url
```

**Comment by aalmiray** [comment] 2015-01-30 17:16
Indeed. We've discussed about removing this warning altogether. Expect changes in the next release.

**Comment by aalmiray** [comment] 2015-01-30 17:18
Duplicate of #141

**Closed by aalmiray** 2015-01-30 17:18 UTC
