### ISSUE TITLE
1.5.2 setSourceDocumentNames is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by ADTC** [asciidoctor/asciidoctor-gradle-plugin#188] opened 2016-05-25 11:22 UTC
I had successfully followed instructions [here](http://asciidoctor.org/docs/asciidoctor-gradle-plugin/) to set up asciidoctor 1.5.0 gradle task. But once I switch to 1.5.2, asciidoctor task refuses to run\* and complains about this:

`Asciidoctor: setSourceDocumentNames is deprecated and will be removed in a future version. Use setIncludes instead. Files are converted to patterns. Some might not convert correctly. FileCollections will not convert`

How do I fix it in the `build.gradle` file which currently uses `sourceDocumentNames`?

\* ignoring `asciidoctor.outputs.upToDateWhen { false }` it shows `UP-TO-DATE` and then `BUILD SUCCESSFUL`

**Comment by ADTC** [comment] 2016-05-25 15:40
Appears that the website is not up-to-date. Instead I followed the Readme [here]() and got it working as follows:

```
asciidoctor {
    sourceDir = file('docs')
    sources { include 'index.adoc' }
    outputDir = file('build/docs')
}
```

I think it will help future explorers to have this here as I could not find a good example for what I wanted to do. **The documentation lacks good examples!**

_The following are optional:_

Copy file to the root of the project (you cannot directly write there in Windows because of [file locking](https://discuss.gradle.org/t/error-with-a-copy-task-on-windows/1803/4)):
```
asciidoctor.doLast {
    copy {
        from 'build/docs/html5'
        into "$projectDir"
        include 'index.html'
    }
}
```

Forcing rebuild each time (even if already up-to-date):
```
asciidoctor.outputs.upToDateWhen { false }
```

**Comment by mojavelinux** [comment] 2016-05-25 17:48
We're in the process of updating the website so that it pulls in the README as an include instead of copying it. Some pages have been updated, but not the one for the Gradle plugin. This needs to be fixed.

The following repository serves as the source of examples for the Gradle plugin. https://github.com/asciidoctor/asciidoctor-gradle-examples The philosophy here is that it's easier to show than to explain.

**Comment by mojavelinux** [comment] 2016-05-25 18:20
Part of the problem is that there's no reference from this README to the examples project. That link should be added prominently at the top of the document.

**Comment by mojavelinux** [comment] 2016-05-25 18:29
Here's the first part of the pull request to integrate the README into asciidoctor.org.

https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/189

Once that is merged, I'll update the page on asciidoctor.org to use it.

**Comment by mojavelinux** [comment] 2016-05-25 18:36
@ADTC If you'd like to incorporate some of these suggestions into the README, we'd certainly welcome those additions.

**Comment by mojavelinux** [comment] 2016-05-25 20:08
The website is now using the content from this README.

**Comment by ADTC** [comment] 2016-05-25 22:41
Thanks for the update. Which suggestions would you like incorporated?

**Comment by ADTC** [comment] 2016-05-25 22:51
I noticed the Asciidoctor home page has these sentences:

> There are plugins available, based on AsciidoctorJ, that integrate the Asciidoctor processor into Apache Maven, Gradle or Javadoc builds.
> In addition to an AsciiDoc processor and a collection of stylesheets, the project provides plugins for Maven, Gradle and Guard and packages for operating systems such as Fedora, Debian and Ubuntu.

But none of the names have any links to the respective plugin pages. Example: [Maven](http://asciidoctor.org/docs/install-and-use-asciidoctor-maven-plugin/), [Gradle](http://asciidoctor.org/docs/install-and-use-asciidoctor-gradle-plugin/)

I found the Docs page has links for AsciidoctorJ, Maven and Gradle. But no mention of Guard.

**Comment by mojavelinux** [comment] 2016-05-26 05:33
> Which suggestions would you like incorporated (and where, too)?

Here's what I have in mind:

* [x] Add link to examples project (see #190)
* [ ] Show snippet that configures sourceDir, sources and outputDir [here](https://github.com/asciidoctor/asciidoctor-gradle-plugin#defining-sources)
* [ ] Show how to copy output file to the root of the project (perhaps in a new tips section)
* [ ] Show how to forcing a rebuild each time, even if already up-to-date (again, in the tips section)

These are definitely useful suggestions. Once changes are made to the README, those changes will be propagated to the website on the next build.

**Comment by mojavelinux** [comment] 2016-05-26 05:36
The asciidoctor.org home page is the README from Asciidoctor core. I agree these should probably be links. We'll need an issue in core to track this change.

> But no mention of Guard.

The Guard plugin is a bit in flux at the moment. It didn't materialize as well as we had hoped, mainly because better solutions came along. It should probably not be mentioned on the home page for now.

**Comment by ADTC** [comment] 2016-05-27 00:50
@mojavelinux see PR #191 thanks :)

**Comment by ADTC** [comment] 2016-05-27 00:58
Btw, by "core" do you mean asciidoctor (the base project) or asciidoctor.org (the website project)?

**Comment by mojavelinux** [comment] 2016-05-27 01:24
"core" refers to asciidoctor/asciidoctor, which is the main processor on which all the other tools rely.

**Comment by ADTC** [comment] 2016-05-27 02:02
@mojavelinux done  asciidoctor/asciidoctor#1782

**Comment by ysb33r** [comment] 2018-06-08 16:09
Can we close this?

**Closed** 2018-07-01 20:23 UTC
