### ISSUE TITLE
clean fails due to some jruby cache

### ISSUE THREAD

**Issue by schauder** [asciidoctor/asciidoctor-gradle-plugin#198] opened 2016-09-08 07:20 UTC
While creating docs with the plugin works nicely the clean task often fails, with an errormessage like this:

```
$ ./gradlew clean
:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean'.
> Unable to delete file: C:\workspaces\junit5-new\build\gems\gems\thread_safe-0.3.5-java\lib\thread_safe\jruby_cache_backend.jar

```

This is on Windows 7 64-bit

Snippet from the build script with (hopefully) all the relevant versions:

```
buildscript {
    dependencies {
        classpath 'org.ysb33r.gradle:vfs-gradle-plugin:1.0-beta8'
        classpath 'commons-httpclient:commons-httpclient:3.1'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
    }
}

plugins {
    id 'org.asciidoctor.convert' version '1.5.3'
    id 'com.github.jruby-gradle.base' version '1.2.1'
}
```

**Comment by mojavelinux** [comment] 2016-09-08 07:25
This seems like an issue with the JRuby Gradle plugin. The Asciidoctor Gradle plugin doesn't manage gems.

**Comment by schauder** [comment] 2016-09-08 07:27
Seems only to happen when the gradle-daemon is used. When running the asciidoc task with --do-daemon the clean works fine after wards.

Also killing the (correct) java process with the taskmanager resolves the problem

**Comment by schauder** [comment] 2016-09-08 07:29
@mojavelinux ok, will create an issue with them.

**Comment by mojavelinux** [comment] 2016-09-08 07:29
So it appears that perhaps the JRuby Gradle plugin is leaving a file open. That's usually the cause of this type of error on Windows. It's imperative to close files when working on Windows. Linux seems to be lenient about it.

**Comment by ysb33r** [comment] 2018-07-01 20:22
Closing this as it a JRuby GRadle issue as this plugin has become less reliant on that plugin due to the most important backends and extensions now being available as JARs.

**Closed by ysb33r** 2018-07-01 20:22 UTC
